kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: potatodiet/hugo-ext

  - name: publish
    image: appleboy/drone-scp
    settings:
      host: "132.145.166.241"
      username: user
      key:
        from_secret: ssh_key
      target: /var/www/potatodiet.ca
      source: public/
      rm: true
